name: Docker Image Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '**'
      - '!*'
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and export
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ${{ github.repository }}:test

    - name: Test image
      run: docker run --rm --tty $GITHUB_REPOSITORY:test ansible --version
