name: Docker Image Publish

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '**'
      - '!*'
  workflow_dispatch:

jobs:

  docker_image_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and export
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ${{ github.repository }}:test

    - name: Test image
      run: docker run --rm --tty $GITHUB_REPOSITORY:test ansible --version

    - name: Push image to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ github.repository }}:latest
